### ISSUE TITLE
assetsIndexUrl这个链接已失效 访问报404 请问bmcl是迁移了吗?

### ISSUE THREAD

**Issue by Ozipino0** [lss233/forge-mod-1.7.10#3]
例如: https://bmclapi2.bangbang93.com/indexes/1.7.10.json 
         https://bmclapi2.bangbang93.com/assets
我这边去他api官网也没找到 如果大佬知道新地址的话麻烦告知一声 谢谢!!

**Comment by lss233** [comment]
应该是移除了。其实可以在本地的 mc 客户端里找到这个文件，读取静态的就行

**Comment by Ozipino0** [comment]
> 应该是移除了。其实可以在本地的 mc 客户端里找到这个文件，读取静态的就行

好的 谢谢解答!
